user_authentication/basic_app/urls.py
from django.conf.urls import url, include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),

]

user_authentication/user_authentication/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/', views.user_logout, name = 'logout'),
    
]

user_authentication/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

user_authentication/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo
from bootstrap_datepicker_plus import DatePickerInput


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta():
        model = UserProfileInfo
        fields = ('date_of_birth', 'profile_pic')

user_authentication/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                                                        { 'user_form':user_form,
                                                          'profile_form':profile_form,
                                                          'registered':registered})
def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse(index))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Login failed")
            return HttpResponse("Invalid login details")

    else:
        return render(request, 'basic_app/login_page.html',{})

user_authentication/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>

        <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
          </div>
            <ul class=" nav navbar-nav">
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
              <li><a href="{% url 'basic_app:register' %}">Sign Up!</a></li>

              {% if user.is_authenticated%}
                <li><a href="{% url 'logout'%}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'basic_app:user_login'%}">Login</a></li>
              {% endif %}
            </ul>
        </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

user_authentication/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html"%}

{% block body_block%}

<div class="jumbotron">
  <h1>Welcome to my Site!</h1>
</div>

{% endblock %}

user_authentication/templates/basic_app/login_page.html
<!DOCTYPE html>

{% extends "basic_app/base.html"%}

{% block body_block%}

<div class="container">
  <h1>Please Login</h1>
  <form  action="{% url 'basic_app:user_login'%}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Enter Username">
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password">
    </div>

    <div class="form-group col-xs-3">
          <input type="submit" class="btn btn-primary" name="submit" value="Login">
    </div>

  </form>

</div>

{% endblock %}

user_authentication/templates/basic_app/registration.html
<!DOCTYPE html>

{% extends "basic_app/base.html"%}
{% load staticfiles %}

{% block body_block%}

<div class="jumbotron">
  {% if registered %}
    <h1>Thanks for registering!</h1>
  {% else %}
    <h1>Register here:</h1>

    <form  method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        {{ user_form.as_table }}
        {{profile_form.as_table}}
      </table>

      <input type="submit" class="btn btn-primary" name="Submit" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}