blog_project/medium/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from blog import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^post/$', views.PostListView.as_view(), name = 'post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name = 'post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name = 'post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name = 'post_remove'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name = 'post_new'),
    url(r'^about/$', views.AboutView.as_view(), name = 'about'),
    url(r'^drafts/$', views.DraftListView.as_view(), name = 'post_draft_list'),

    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name = 'add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name = 'comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name = 'comment_remove'),

    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name = 'post_publish'),

]

blog_project/medium/medium/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^accounts/login/$', views.LoginView.as_view(), name = 'login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name = 'logout', kwargs = {'next_page':'blog/'}),
    url(r'^admin/', admin.site.urls),
]

blog_project/medium/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk':self.pk})
# Method to put publish_date for the blog
    def publish(self):
        self.published_date = timezone.now()
        self.save()

#Method to handle comments on the blog Post
    def approve_comments(self):
        return self.comments.filter(approved_comment = True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments')
    author = models.CharField(max_length = 200)
    text = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_list", kwargs={'pk':self.pk})

    def __str__(self):
        return self.text

blog_project/medium/blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
                    'title':forms.TextInput(attrs = {'class':'textinputclass'}),
                    'text': forms.Textarea(attrs = {'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
                    'author':forms.TextInput(attrs = {'class':'textinputclass'}),
                    'text': forms.Textarea(attrs = {'class':'editable medium-editor-textarea'})
        }

blog_project/medium/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from blog import models
from django.urls import reverse_lazy
from blog.forms import PostForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.decorators import login_required

class IndexView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    #context_object_name = 'posts'
    model = models.Post

    def get_queryset(self):
        return models.Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = models.Post
    #context_object_name = 'post_detail'

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = models.Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = models.Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = models.Post
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = models.Post

    def get_queryset(self):
        return models.Post.objects.filter(published_date__isnull = True).order_by('created_date')


################################################
#Comment Section

@login_required
def post_publish(request, pk):
    post = get_object_or_404(models.Post, pk = pk)
    post.publish()
    return redirect("blog:post_detail", pk = pk)


@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(models.Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect("blog:post_detail",pk = post.pk)
    else:
        form= CommentForm()
    return render(request, 'blog/comment_form.html', {'form':form})


#######
#Approve a Comment

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment,pk = pk)
    comment.approve()
    return redirect("blog:post_detail", pk = comment.post.pk)

######Remove CommentForm

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(models.Comment,pk = pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect("blog:post_detail", pk = post_pk)

blog_project/medium/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>Here you can read about my site</h1>
{% endblock %}

blog_project/medium/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
  </head>
  <body>
    <nav class="navbar">
        <ul class=" nav navbar-nav">
          <li class=""><a href="{% url 'blog:post_list' %}">My Tech Blog</a></li>
          <li><a href="{% url 'blog:about' %}">About</a></li>
          <li><a href="www.github.com">GitHub</a></li>
          <li><a href="www.linkedin.com">LinkedIn</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'blog:post_new' %}">New Post</a></li>
            <li><a href="{% url 'blog:post_draft_list' %}">Drafts</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a>Welcome {{user.username}} </a></li>

          {% else %}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>

          {% endif %}

        </ul>
    </nav>

    <div class="content container">
      
          {% block body_block %}

          {% endblock %}
    </div>


  </body>
</html>

blog_project/medium/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>New Comment</h1>
  <form class="post-form"  method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Add Comment</button>
    
  </form>
{% endblock %}

blog_project/medium/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>Welcome to my blog Site.</h1>
{% endblock %}

blog_project/medium/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <form  method="POST">
    {% csrf_token %}
    <p>Are you sur eyou want to delete {{object}}?</p>
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>

{% endblock %}

blog_project/medium/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block body_block %}

  <h1 class="posttitle">{{post.title}}</h1>
  {% if post.published_date %}
    <div class="date postdate">
      {{post.published_date}}
    </div>
  {% else %}
      <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
  {% endif %}

  <p class = 'postcontent'>{{ post.text|safe|linebreaksbr }}</p>

  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
  {% endif %}

  <hr>

  <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
  <div class="container">
    {% for comment in post.comments.all %}
      <br>
      {% if user.is_authenticated or comment.approved_comment %}
        {{comment.created_date}}
        {% if not comment.approved_comment%}
        <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
        {% endif %}

        <p>{{comment.text|safe|linebreaks}}</p>
        <p>Posted By:{{comment.author}}</p>
      {% endif %}
      {% empty %}
      <p>No Comments</p>
    {% endfor %}
  </div>

{% endblock %}

blog_project/medium/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block body_block %}

  {% for post in posts %}
    <div class="post">
      <p class="date">created: {{post.created_date | date:'d-m-Y'}}</p>
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}"></a>{{post.title}}</h1>
      <p>{{post.text|truncatechars:200}}</p>
    </div>
  {% endfor %}

{% endblock %}

blog_project/medium/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block body_block %}
  <h1>New Post</h1>
  <form class="post-form"  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>

  <script type="text/javascript">
    var editor = new MediumEditor('.editable');
  </script>
{% endblock %}

blog_project/medium/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block body_block %}

  <div class="container">
    <h1>Welcome to my list of Blogs.</h1>
    {% for post in post_list %}
      <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <div class="date">
          <p>Published On: {{post.published_date | date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
      </div>
    {% endfor %}
  </div>

{% endblock %}