class_based_views/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name = 'list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailsView.as_view(), name = 'detail'),
    url(r'^create/$', views.CreateSchoolView.as_view(), name = 'create'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdateSchoolView.as_view(), name = 'update'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteSchoolView.as_view(), name = 'delete')
]

class_based_views/class_based_views/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^admin/', admin.site.urls),
]

class_based_views/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length = 50)
    principal = models.CharField(max_length = 50)
    location = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length = 50)
    age = models.IntegerField()
    school = models.ForeignKey(School,related_name = 'students',on_delete = models.CASCADE)

    def __str__(self):
        return self.name

class_based_views/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from basic_app import models
from django.urls import reverse_lazy

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailsView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'

class CreateSchoolView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class UpdateSchoolView(UpdateView):
    fields = ('principal',)
    model = models.School

class DeleteSchoolView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

class_based_views/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>

        <nav class="navbar navbar-default">
            <ul class=" nav navbar-nav">
              <li class="navbar-brand"><a href="{% url 'basic_app:list' %}">Schools</a></li>
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
              <li><a href="#"></a></li>
            </ul>
        </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

class_based_views/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
  <h1>Delete: {{school.name}}?</h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

class_based_views/basic_app/templates/basic_app/school_details.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
  <div class="jumbotron">

    <h1>Below are the details of the selected school:</h1>
    <h2>School Details:</h2>

    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h2>Students in this school are:</h2>

    {% for student in school_detail.students.all %}
      <p>{{student.name}}</p>
    {% endfor %}

  </div>

  <div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
       <a class="btn btn-warning" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete School</a></p>
  </div>

{% endblock %}

class_based_views/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
  <h1>
    {% if form.instance.pk %}
      Update School:
    {% else %}
      Create School:
    {% endif %}
  </h1>

  <form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

{% endblock %}

class_based_views/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
  <div class="jumbotron">
    <h1>Welcome to List of all Schools:</h1>

    <ol>
      {% for school in schools %}
        <li><a href="{{school.id}}">{{school.name}}</a></li>
      {% endfor %}
    </ol>

    <div class="container">
      <p><a class="btn btn-primary" href="{% url 'basic_app:create' %}">Create School</a></p>
    </div>
  </div>
{% endblock %}

class_based_views/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>

        <nav class="navbar navbar-default">
            <ul class=" nav navbar-nav">
              <li class="navbar-brand"><a href="{% url 'basic_app:list' %}">Schools</a></li>
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
              <li><a href="#"></a></li>
            </ul>
        </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

class_based_views/templates/index.html
{% extends "base.html" %}

{% block body_block%}
  <div class="jumbotron">
    <h1>Welcome to HomePage!</h1>
  </div>
{% endblock %}